// <auto-generated />
using System;
using Client.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client.Infrastructure.Migrations
{
    [DbContext(typeof(FdmDbContext))]
    [Migration("20241124203819_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Client.Domain.Entites.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppSettingType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Client.Domain.Entites.CategoryGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoryGroups");
                });

            modelBuilder.Entity("Client.Domain.Entites.CategoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryGroupId");

                    b.ToTable("CategoryItems");
                });

            modelBuilder.Entity("Client.Domain.Entites.DownloadQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DownloadQueues");
                });

            modelBuilder.Entity("Client.Domain.Entites.FileTypeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtensions")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileTypeGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 11, 25, 0, 8, 19, 444, DateTimeKind.Local).AddTicks(68),
                            FileExtensions = "zip rar",
                            IsDeleted = false,
                            Title = "فایل های فشرده",
                            Updated = new DateTime(2024, 11, 25, 0, 8, 19, 444, DateTimeKind.Local).AddTicks(79)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 11, 25, 0, 8, 19, 444, DateTimeKind.Local).AddTicks(86),
                            FileExtensions = "txt docx xls",
                            IsDeleted = false,
                            Title = "اسناد",
                            Updated = new DateTime(2024, 11, 25, 0, 8, 19, 444, DateTimeKind.Local).AddTicks(87)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 11, 25, 0, 8, 19, 444, DateTimeKind.Local).AddTicks(89),
                            FileExtensions = "mp3 wave",
                            IsDeleted = false,
                            Title = "موسیقی",
                            Updated = new DateTime(2024, 11, 25, 0, 8, 19, 444, DateTimeKind.Local).AddTicks(89)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2024, 11, 25, 0, 8, 19, 444, DateTimeKind.Local).AddTicks(91),
                            FileExtensions = "exe msi",
                            IsDeleted = false,
                            Title = "برنامه ها",
                            Updated = new DateTime(2024, 11, 25, 0, 8, 19, 444, DateTimeKind.Local).AddTicks(91)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2024, 11, 25, 0, 8, 19, 444, DateTimeKind.Local).AddTicks(93),
                            FileExtensions = "mpeg 3gp avi flv",
                            IsDeleted = false,
                            Title = "تصویری",
                            Updated = new DateTime(2024, 11, 25, 0, 8, 19, 444, DateTimeKind.Local).AddTicks(94)
                        });
                });

            modelBuilder.Entity("Client.Domain.Entites.CategoryItem", b =>
                {
                    b.HasOne("Client.Domain.Entites.CategoryGroup", "CategoryGroup")
                        .WithMany()
                        .HasForeignKey("CategoryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
