// <auto-generated />
using System;
using Client.Infrastructure.DbContexts.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client.Infrastructure.Migrations
{
    [DbContext(typeof(FdmAppDbContext))]
    partial class FdmAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Client.Domain.Entites.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppSettingType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppSettingType = 0,
                            Created = new DateTime(2025, 2, 7, 12, 21, 51, 351, DateTimeKind.Local).AddTicks(3141),
                            Key = "TempSavePathTextbox",
                            Updated = new DateTime(2025, 2, 7, 12, 21, 51, 351, DateTimeKind.Local).AddTicks(3144),
                            Value = "C:\\Users\\Sattec\\AppData\\Roaming\\FDM"
                        });
                });

            modelBuilder.Entity("Client.Domain.Entites.CategoryGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoryGroups");
                });

            modelBuilder.Entity("Client.Domain.Entites.CategoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryGroupId");

                    b.ToTable("CategoryItems");
                });

            modelBuilder.Entity("Client.Domain.Entites.DownloadQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DownloadQueues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 7, 12, 21, 51, 350, DateTimeKind.Local).AddTicks(2466),
                            IsDeleted = false,
                            Title = "صف اصلی",
                            Updated = new DateTime(2025, 2, 7, 12, 21, 51, 350, DateTimeKind.Local).AddTicks(2469)
                        });
                });

            modelBuilder.Entity("Client.Domain.Entites.FileTypeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtensions")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileTypeGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 7, 12, 21, 51, 346, DateTimeKind.Local).AddTicks(2499),
                            FileExtensions = "zip rar",
                            FolderName = "Compressed",
                            IsDeleted = false,
                            SavePath = "C:\\Users\\Sattec\\Downloads\\Compressed",
                            Title = "فایل های فشرده",
                            Updated = new DateTime(2025, 2, 7, 12, 21, 51, 348, DateTimeKind.Local).AddTicks(7183)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 2, 7, 12, 21, 51, 349, DateTimeKind.Local).AddTicks(4219),
                            FileExtensions = "txt docx xls",
                            FolderName = "Documents",
                            IsDeleted = false,
                            SavePath = "C:\\Users\\Sattec\\Downloads\\Documents",
                            Title = "اسناد",
                            Updated = new DateTime(2025, 2, 7, 12, 21, 51, 349, DateTimeKind.Local).AddTicks(4222)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 2, 7, 12, 21, 51, 349, DateTimeKind.Local).AddTicks(4758),
                            FileExtensions = "mp3 wave",
                            FolderName = "Music",
                            IsDeleted = false,
                            SavePath = "C:\\Users\\Sattec\\Downloads\\Music",
                            Title = "موسیقی",
                            Updated = new DateTime(2025, 2, 7, 12, 21, 51, 349, DateTimeKind.Local).AddTicks(4760)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2025, 2, 7, 12, 21, 51, 349, DateTimeKind.Local).AddTicks(5276),
                            FileExtensions = "exe msi",
                            FolderName = "Video",
                            IsDeleted = false,
                            SavePath = "C:\\Users\\Sattec\\Downloads\\Video",
                            Title = "برنامه ها",
                            Updated = new DateTime(2025, 2, 7, 12, 21, 51, 349, DateTimeKind.Local).AddTicks(5278)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2025, 2, 7, 12, 21, 51, 349, DateTimeKind.Local).AddTicks(5682),
                            FileExtensions = "mpeg 3gp avi flv",
                            FolderName = "Compressed",
                            IsDeleted = false,
                            SavePath = "C:\\Users\\Sattec\\Downloads\\Compressed",
                            Title = "تصویری",
                            Updated = new DateTime(2025, 2, 7, 12, 21, 51, 349, DateTimeKind.Local).AddTicks(5683)
                        });
                });

            modelBuilder.Entity("Client.Domain.Entites.CategoryItem", b =>
                {
                    b.HasOne("Client.Domain.Entites.CategoryGroup", "CategoryGroup")
                        .WithMany()
                        .HasForeignKey("CategoryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
