global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Client.Domain.Entites.Base;
global using Client.Domain.Enums;
global using Client.Domain.Dtos;
global using Client.Domain.Dtos.Response;
global using Client.Domain.Entites;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using Client.Domain.Interfaces.Dto;
global using Client.Domain.Interfaces.Services;
global using Client.Domain.Interfaces.Repositories;
global using Client.Domain.Resources;
global using Client.Domain.Dtos.Response.AppSetting;
global using System.ComponentModel.DataAnnotations.Schema;
//final